name: flutterfire_version_manager
description: A CLI tool to lock all FlutterFire dependencies to compatible versions
version: 0.1.3
homepage: https://github.com/IO-Design-Team/flutterfire_version_manager

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.18.1
  pub_api_client: ^2.4.0
  pubspec: ^2.3.0

dev_dependencies:
  rexios_lints: ^5.0.0

executables:
  ffvm: ffvm
